services:
  api:
    image: node:20.19.0-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "8081:8081"
    command: sh -c "npm install --legacy-peer-deps &&  npx prisma generate && npm run prisma:migrate:deploy && sh ./check-seeded.sh && npm start"
    depends_on:
      - postgres
  ux:
    image: node:20.19.0-alpine
    working_dir: /app
    volumes:
      - ./ux:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"


  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaunax
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
